apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: {{ .Values.frontend.type }}
  ports:
  - port: {{ .Values.frontend.externalPort }}
    targetPort: {{ .Values.frontend.internalPort }}
    protocol: TCP
  selector:
    app: guestbook
    tier: frontend
