{{- if and .Values.redis.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
    name: guestbook
    labels:
        app: redis
        chart: ''
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
type: Opaque
data:
  redis-password: {{ .Values.redis.password }}
{{- end -}}
